Repository automate-lfs/jhalfs, pull requests merged in 2019-05, with the labels that each got.

#10 Bryan5989 patch 1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: branch-maintenance

#11 Update issue templates
  .github/ISSUE_TEMPLATE/ask-a-question.md
Labels: branch-maintenance

#14 Fix gen install 1
  BLFS/xsl/gen-install.xsl
  BLFS/xsl/scripts.xsl
Labels: bug, enhancement

#7 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, repository-change

#12 Add issue templates
  .github/ISSUE_TEMPLATE/ask-a-question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: enhancement, repository-change
